### ISSUE TITLE
Help with Path* methods

### ISSUE THREAD

**Issue by regevbr** [pirix-gh/ts-toolbelt#10]
#### Describe your question
I'm trying to rewrite the entire typings for underscore in the @typings/underscore library.
One of the methods is [map](https://underscorejs.org/#map) and one of it's variations is to take a list and map every object in it to the value of the specified path of that object. e.g.
```ts
_.map( [{arr: [5, 1, 7]}, {arr: [3, 2, 1]}], ['arr']); // should be [[5, 1, 7],[3, 2,1]]
```
The best I got so far is
```ts
interface List<T> {

    [index: number]: T;

    length: number;

}
type TypeOfList<T> = T extends List<infer V> ? V : any;

map<T extends TypeOfList<V>, K extends string[], V extends List<any> = List<T>>(
    list: V,
    iterator: A.Cast<K, O.PathValid<T, K>>,
    context?: any): Array<U.Nullable<O.Path<T, K>>>;
```

But when I try the example above I get  
`Typescript type instantiation is excessively deep and possibly infinite`

@pirix-gh can you please help?

**Comment by pirix-gh** [comment]
Wow this is a crazy quest you've started! (Personally, I use Ramda (it's ok/well typed))

I doubt that anyone would be able to guess the proper ouput type as it's implementation-dependent.

But you could get a wider type though that is the return type of the `iteratee` as an array/list:
`ReturnOf<Iteratee>[]`

Where `Iteratee` is the generic type of the `iteratee` function that is passed to `map`.

And if you get this error it means that you're either doing something too complex or what I've explained [over here](https://github.com/pirix-gh/ts-toolbelt/issues/5)

**Comment by regevbr** [comment]
@pirix-gh I'm not sure I follow...
The example I presented doesn't work as a standalone so it has nothing to do with overloading of the Iteratee ...

**Comment by pirix-gh** [comment]
Then I am not sure of what you're doing. I never used underscore. I just saw that the docs specify the second argument but I see that you're passing an array? But I can't see this anywhere in the docs.

So I guess you're trying to do some kind of function type overload. So I think that you're doing some kind of selection. You should write a mapped type that picks the right sub-elements.

**Comment by regevbr** [comment]
The docs state vaguely (and the code backs it up) that iteratee value is actually passed to [_.iteratee](https://underscorejs.org/#iteratee) and then if you pass a string path array, it will be passed to  [_.property](https://underscorejs.org/#property) so my use case is valid.

But all of this has nothing to do with my problem, as the example above simply fails regardless of the other overloaded methods (which I can send here if you want) 

It seems that the issue only happens because we pass an explicit array (instead of spread args)... Where in the following example it works good:
```ts
_.map( [{arr: {arr2: [5, 1, 7]}}, {arr: {arr2: [5, 1, 7]}}], 'arr', 'arr2');
```

Can you tell why that happens?

**Comment by regevbr** [comment]
The following example does work with the original code (no spread).
It seems that it is related to how Typescript realizes the type of the array.
```ts
_.map( [{arr: {arr2: [5, 1, 7]}}, {arr: {arr2: [5, 1, 7]}}], ['arr', 'arr2'] as ['arr', 'arr2']);
```

One can try to use 

```ts
_.map( [{arr: {arr2: [5, 1, 7]}}, {arr: {arr2: [5, 1, 7]}}], ['arr', 'arr2'] as const);
```

But then the array becomes `readonly` and can't be passed into your library types...

**Comment by pirix-gh** [comment]
You can, use `T.Writable` before passing it to other types. Sorry that I can't help you more atm. I am very busy.

**Comment by regevbr** [comment]
That works!
Writable of Tuple is not exported - I will open a bug for it.
