### ISSUE TITLE
Feature Request - Function.Partial

### ISSUE THREAD

**Issue by tdreyno** [pirix-gh/ts-toolbelt#100]
#### Is your feature request related to a problem?

I am adding a function which partially applies functions in my library and would love a type to represent it. These kind of variadic types are hard to write and maintain, which is why ts-toolbelt is so great.

#### Describe the solution you'd like

I would like to see a `Function.Partial` (or maybe another name so as to not collide/confuse with the core `Partial` type) which would be used for something like lodash's `partial` application function: https://lodash.com/docs#partial

Or, maybe this already exists with a different name?

#### Describe alternatives you've considered

I have found a solid solution in another library (https://github.com/commonlyjs/commonly/blob/master/packages/type/Function/PartialFunction/PartialFunction.ts), but would love to just use ts-toolbelt alone.

#### Teachability, Documentation, Adoption, Migration Strategy

N/A

**Comment by pirix-gh** [comment]
Hi @tdreyno, I think that we have a good building block for this. https://pirix-gh.github.io/ts-toolbelt/modules/_function_curry_.html

It is able to handle placeholders in any position. When using a placeholder, just make sure that it is of type https://pirix-gh.github.io/ts-toolbelt/modules/_any_x_.html

This version could bring a `Partial` application type, with a few modifications of course. Can you try it and let me known what you think?

Here's an example:

```ts
declare function curry<Fn extends F.Function>(f: Fn): F.Curry<Fn>

const __ = {} as A.x

const toCurry = (name: string, age: number, single: true, nicknames: string) => true
const curried = curry(toCurry)

const test00: boolean = curried(__, 26)(__, true, 'JJ')('Jane') // boolean
const test01: boolean = curried('Jane', 26, true, __)('JJ')     // boolean
```
