### ISSUE TITLE
Excessively deep type error with TS #37537

### ISSUE THREAD

**Issue by ahejlsberg** [pirix-gh/ts-toolbelt#104]
An excessively deep type error is issued with https://github.com/microsoft/TypeScript/pull/37537. Looks like it can be fixed by switching from `Extends` to `Equals` here:

https://github.com/pirix-gh/ts-toolbelt/blob/master/src/List/Repeat.ts#L18

**Comment by pirix-gh** [comment]
Fix is out. Sorry about this :)
