### ISSUE TITLE
add ValueType and allow Object.At  O extends {}

### ISSUE THREAD

**Issue by xiaoxiangmoe** [pirix-gh/ts-toolbelt#107]
#### Is your feature request related to a problem?

```ts
import { mapValues } from 'lodash';
import * as querystring from 'querystring';

export type ValueType<T extends {}> = T[keyof T];

export type LoosePropertyType<
  T extends {},
  K extends string
> = K extends keyof T ? T[K] : never;

interface APIs {
  readonly server1: {
    readonly getUserProfile: {
      readonly Parameter: {
        readonly id: string;
      };
      readonly Response: {
        '200': {
          readonly id: string;
          readonly name: string;
          readonly gender: boolean;
        };
      };
    };
  };
}

const ApiData = {
  server1: {
    getUserProfile: {
      url: 'www.foo.com/profile',
    },
  },
};

const myFetch = (mapValues(ApiData, server =>
  mapValues(server, ({ url }) => (requestParams: any) =>
    fetch(url + querystring.stringify(requestParams)).then(x => {
      if (x.status === 200) {
        return x.json();
      }
      throw new Error();
    }),
  ),
) as any) as {
  [namespace in keyof APIs]: {
    [operationId in keyof APIs[namespace]]: (
      param: LoosePropertyType<APIs[namespace][operationId], 'Parameter'>,
    ) => Promise<
      ValueType<LoosePropertyType<APIs[namespace][operationId], 'Response'>>
    >;
  };
};
```
#### Describe the solution you'd like

* add ValueType
* change `type AtLoose<O extends object, K extends Key> = O extends unknown ? AtStrict<O, K> : never;` to `type AtLoose<O extends {}, K extends Key> = O extends unknown ? AtStrict<O, K> : never;`

**Comment by pirix-gh** [comment]
Hi there, you can use `UnionOf` to do this https://pirix-gh.github.io/ts-toolbelt/modules/_object_unionof_.html

**Comment by xiaoxiangmoe** [comment]
@pirix-gh Sorry, I tried it and it doesn't seem to work.

**Comment by xiaoxiangmoe** [comment]
Sorry, I tried it and it doesn't seem to work.

**Comment by pirix-gh** [comment]
Oops sorry, I misunderstood your demand. This is kind of strange though. I can't edit `At` for type safety purposes. It happens that TypeScript does not infer the expected type correctly. In those cases, I invite you to use `Cast` or `&`.

Here's your code:

```ts
type t = {
  [namespace in keyof APIs]: {
    [operationId in keyof APIs[namespace]]: (
      param: O.At<APIs[namespace][operationId] & {}, 'Parameter'>,
    ) => Promise<
      O.UnionOf<O.At<APIs[namespace][operationId] & {}, 'Response'> & {}>
    >;
  };
};
```

I used `& {}` to cast the type to `object` since we are sure that it is an object. This is an odd error though, maybe it should be reported as a bug to the ts team.

**Comment by xiaoxiangmoe** [comment]
How can I describe this problem and report a bug to TS? I am not very familiar with the mechanism of TS.

**Comment by pirix-gh** [comment]
The same way you opened an issue here. But you must make your example clearer and ask them why is `APIs[namespace][operationId]` not inferred as an object. Maybe you should try to simplify your code, just keep the type part. Good luck!

**Comment by xiaoxiangmoe** [comment]
Thank you.
