### ISSUE TITLE
Add AtLeastOne type

### ISSUE THREAD

**Issue by thesunny** [pirix-gh/ts-toolbelt#108]
#### Is your feature request related to a problem?
I need a way to test if a type has at least one property

#### Describe the solution you'd like
Solution:

```ts
type AtLeastOne<T, U = {[K in keyof T]: Pick<T, K> }> = Partial<T> & U[keyof U]
```

Which came from https://stackoverflow.com/questions/48230773/how-to-create-a-partial-like-that-requires-a-single-property-to-be-set/48244432

#### Teachability, Documentation, Adoption, Migration Strategy

This can be used where there is a hard requirement for a single property.

Two examples:

- A where clause in a database ORM where you don't want the developer to accidentally delete the entire database so you specify they need at least one property.
- My specific use case is a Prettify function for any type. In order to keep the Prettify working correctly with a function, I need to detect when a function has additional properties. For example, in nextjs, there is a React Component with a `getInitialProps` function. I want to prettify that `getInitialProps` property. However, I don't want to do it for functions that don't have the property because it then adds an extraneous `& {}` to the function type. This allows me to detect that.

**Comment by pirix-gh** [comment]
Hey @thesunny, thanks for submitting this! The feature is out. I wrote a more flexible and improved version of the one you posted. Here's a few examples:

* This will require at least one

```ts
import {O} from 'ts-toolbelt'

type O = {
    a: 1
    b: 2
    c: 3
}

type t0 = O.AtLeast<O>
```

* Or say which ones are at least required

```ts
import {O} from 'ts-toolbelt'

type O = {
    a: 1
    b: 2
    c: 3
}

type t1 = O.AtLeast<O, 'a' | 'b'>
```

* And it will work on unions too

```ts
import {O} from 'ts-toolbelt'

type O = {
    a: 1
    b: 2
    c: 3
} | {
    a: 4
    d: 5
    e: 6
}

type t2 = O.AtLeast<O, 'a' | 'b' | 'e'>
```

Let me know if we can improve anything.

Cheers

**Comment by thesunny** [comment]
Oh wow! Nice!

Thanks for the quick response.
