### ISSUE TITLE
Shorthand for Partial<MyType, 'deep'>

### ISSUE THREAD

**Issue by mesqueeb** [pirix-gh/ts-toolbelt#109]
#### Is your feature request related to a problem?
With plain TS, you can write `Partial<>` to make all props partial.
However, this doesn't work deeply.

To do it deep I use TS-Toolbelt:
```ts
O.Optional<MyType, keyof MyType, 'deep'>
```

#### Describe the solution you'd like
I'd love the shorthand for the above:
```ts
O.Partial<MyType, 'deep'>
```

#### Describe alternatives you've considered
I can write the long hand, as I do now.

#### Teachability, Documentation, Adoption, Migration Strategy
I think it would be self-explanatory.

Thanks again! 😉

**Comment by pirix-gh** [comment]
Hey @mesqueeb, this is already possible, though it isn't documented:

```ts
import 'ts-toolbelt'
import {OptionalDeep} from 'Object/Optional'

type O = {
    a: 1
    b: 2
    c: O
}

type t2 = OptionalDeep<O>
```

**Comment by mesqueeb** [comment]
@pirix-gh 
Thanks!

I see I have to import the entire library for this.

Would be great if you could expose this to the `O` exports!!! < 3

**Comment by mesqueeb** [comment]
@pirix-gh Is it possible to add an alias for
```ts
import {OptionalDeep} from 'Object/Optional'

OptionalDeep<MyType>
```

that looks like this:
```ts
import {O} from 'ts-toolbest'

O.Partial<MyType, 'deep'>
```
I think it's what most TS developers might come looking for when they want to do a deep Partial

**Comment by pirix-gh** [comment]
Yes, we can. Would you mind opening a PR?
