### ISSUE TITLE
T.Writable is not exported

### ISSUE THREAD

**Issue by regevbr** [pirix-gh/ts-toolbelt#11]
#### Describe the bug
T.Writable is not exported.
Currently can only be accessed by 
```ts
import {Writable} from 'ts-toolbelt/out/types/src/Tuple/Writable';
```

#### Possible Solution
Add to `Tuple/_api.d.ts`
```ts
export { Writable } from './Writable';
```

**Comment by regevbr** [comment]
I will create a quick PR

**Comment by pirix-gh** [comment]
That's really bad luck, sorry. I forgot to add it in `Tuple/_api`. Thanks.

**Comment by regevbr** [comment]
Sure thing - probably happens because you skipped the tests for it :-) - I added some as well.

**Comment by pirix-gh** [comment]
TypeDoc is giving me problems generating the docs when using `readonly`... They don't support it
