### ISSUE TITLE
Strict Object Literals

### ISSUE THREAD

**Issue by waynevanson** [pirix-gh/ts-toolbelt#110]
#### Describe your question

I'm trying to create the `isLiteral` function below, fully typed.

If it is a literal, it means that it is not a class derived from `Object`

```ts
const isLiteral = <T>(a: T): a is ??? =>
  a instanceof Object && a.constructor.name === "Object";

// returns true
isLiteral({})

isLiteral({ name: 'shrek' }) 

isLiteral({ 0: 'shrek' }) 

// returns false
isLiteral([])

isLiteral(class) 

class Classy { }
isLiteral(new Classy()) 

isLiteral(Classy) 

```
Do you have anything similar, a place to look? I can't assert the difference between class and an object, as they have the same prototype.

**Comment by pirix-gh** [comment]
I don't think this is possible. I got this so far:

```ts
declare function isLiteral(c: (new (...args: any[]) => any)): false
declare function isLiteral(c: any[]): false
declare function isLiteral(c: object): true
```

You should just return `boolean` instead :)

**Comment by pirix-gh** [comment]
https://github.com/microsoft/TypeScript/issues/3841

**Comment by waynevanson** [comment]
@pirix-gh RIP

Thank you for looking into this.
