### ISSUE TITLE
Add IsStringLiteral, IsNumericLiteral and IsLiteral

### ISSUE THREAD

**Issue by thesunny** [pirix-gh/ts-toolbelt#111]
#### Is your feature request related to a problem?
I need the ability to identity a literal. A use case, for example, is when creating a validation function like in JSON Schema where we wish to define an `enum`. The value of an `enum` are accepted as an array of literal strings or numbers. To do this, the user must specify the array `as const`. If the user does not, the array will appear as `number` types. This should create a TypeScript array.

#### Describe the solution you'd like
A function that lets us identify literals.

#### Describe alternatives you've considered
I wrote the missing function.

#### Teachability, Documentation, Adoption, Migration Strategy
Here is the code I wrote:

```ts
type IsStringLiteral<T> = T extends string
  ? string extends T
    ? B.False
    : B.True
  : B.False

type IsNumericLiteral<T> = T extends number
  ? number extends T
    ? B.False
    : B.True
  : B.False

type IsLiteral<T> = B.Or<IsStringLiteral<T>, IsNumericLiteral<T>>
```

Description:

Identify if a type is a string literal, numeric literal or any literal. It works even if the passed in type is an `or` of literals like `"a" | "b" | "c"|`.

**Comment by pirix-gh** [comment]
Hey @thesunny, it's out in a few minutes
