### ISSUE TITLE
Is there a way to sponsor / donate that is not recurring

### ISSUE THREAD

**Issue by thesunny** [pirix-gh/ts-toolbelt#116]
#### Describe your question
Is there a way to provide a one-time donation. Possibly an email to use with PayPal?

The only method I could find was to use a recurring sponsor and then cancelling it immediately but felt like that was the wrong approach.

It would be nice to have a way to say thanks with a donation that doesn't need to recur.

#### Search tags, topics
sponsor
donate
donation

**Comment by pirix-gh** [comment]
Thank you so much, there you go: https://www.buymeacoffee.com/pirix

**Comment by pirix-gh** [comment]
Thanks @tonivj5!

**Comment by thesunny** [comment]
@pirix-gh FYI, I'm the "Someone" that contributed 20 rockets.

Not asking for credit. Just wanted to let you know that I appreciate your work. Your library is useful and the last time I posted an issue, you were also responsive.

**Comment by pirix-gh** [comment]
Amazing, thank you so much @thesunny. I feel very rewarded, thank you!

I will always be there to help out, and do as much as I can to share my knowledge.
