### ISSUE TITLE
Question to approach

### ISSUE THREAD

**Issue by b2whats** [pirix-gh/ts-toolbelt#118]
Please tell us why you use this construction
```
... extends infer X
```
for example here https://github.com/pirix-gh/ts-toolbelt/blob/master/src/Object/PathValid.ts#L42

How does it avoid an error
```
Type instantiation is excessively deep and possibly infinite.
```

**Comment by tonivj5** [comment]
Maybe https://github.com/pirix-gh/ts-toolbelt/issues/5 resolves your question

**Comment by b2whats** [comment]
Thanks 🤗
