### ISSUE TITLE
ValidPath without const assertion?

### ISSUE THREAD

**Issue by asgerhallas** [pirix-gh/ts-toolbelt#119]
## 🤔 Question

I'm new to this library, and am still trying to get my head around it. It's very impressive! :)

In this sample https://pirix-gh.github.io/ts-toolbelt/modules/_object_pathvalid_.html there's the following code: 

    const test0 = getAt(state,          ['case', 'name'] as const) // {c: number}

Why is const needed? And is there a way to make it work without the const assertion?

Hope you can help.

**Comment by pirix-gh** [comment]
Hi there,

Without a const assertion, the type of `['case', 'name']` would be narrowed to `string[]` that's all. Depending on your type safety needs, you would choose `as const` or not.

**Comment by asgerhallas** [comment]
I somehow missed your answer, sorry! What I meant was that, I'd like the type safety to be enforced by the function signature, so the caller does not have to add `as const`, but still only be able to pass expected strings in the array. It's easy for a caller to forget `as const` and thus we will not catch errors now or when the allowed string values change in the future.

**Comment by millsp** [comment]
It's a TypeScript limitation, I know how inconvenient this is. To work around that, the only solution is to take rest parameters instead. Or you could have this Maybe this can help you:

- https://github.com/millsp/ts-toolbelt/issues/154
- https://github.com/microsoft/TypeScript/issues/30680

**Comment by asgerhallas** [comment]
Thanks a lot for your swift reply :) 

I'll look into those links right away!

**Comment by millsp** [comment]
I posted a solution to this problem here in https://github.com/microsoft/TypeScript/issues/30680. It will land soon in ts-toolbelt.

**Comment by asgerhallas** [comment]
This is amazing, thank you for doing this!
