### ISSUE TITLE
Can we transform a tuple containing a union type into a union type of tuples?

### ISSUE THREAD

**Issue by ruizb** [pirix-gh/ts-toolbelt#120]
#### Describe your question

Hello there,

I couldn't find a better title, lacking some TypeScript "advanced" vocabulary. Anyway, I was about to post an issue on the TypeScript repository, but since I've witnessed incredible magic with this library, I wonder if my problem can be fixed using ts-toolbelt 🙂 

Here's my problem:

```ts
type A = [number, 'yes'] | [number, 'no'] | [string, 'maybe']
type B = 'yes' | 'no' | 'maybe'

declare const b: B
const a: A = (b === 'yes' || b === 'no') ? [12, b] : ['12', 'maybe']
```

I've got a TS2322 error on `a`:

```txt
Type '[number, "yes" | "no"] | [string, "maybe"]' is not assignable to type 'A'.
  Type '[number, "yes" | "no"]' is not assignable to type 'A'.
    Type '[number, "yes" | "no"]' is not assignable to type '[number, "yes"]'.
      Type '"yes" | "no"' is not assignable to type '"yes"'.
        Type '"no"' is not assignable to type '"yes"'.
```

When I use an object, I don't get any error and it works as intended:

```ts
type C = { value: number, tag: 'yes' } | { value: number, tag: 'no' } | { value: string, tag: 'maybe' }

const c: C = (b === 'yes' || b === 'no') ? { value: 12, tag: b } : { value: '12', tag: 'maybe' }
```

However, I'd like to use a tuple because I don't want to bother finding names for the values I want to keep together. Since tuples and objects are homomorphic, I don't understand why it works with objects, but not with tuples.

So here's my question: **Is it possible to turn a `[number, 'a' | 'b']` into a `[number, 'a'] | [number, 'b']`?**

I understand there might be performance issues with this: if a tuple has a union type with tens of possible values (or worse, several union types), it will generate a lot of possible tuples in the end. Nonetheless, I wonder if it's possible to achieve this with the the helpers available on this lib 🤔 

#### Search tags, topics
#typescript #tuple #transform #union #type #distribute

**Comment by ruizb** [comment]
I think I got things mixed up 😅  since `A` is already written as a union type of tuples, I feel like the TS error I'm having cannot be fixed with ts-toolbelt 😞

**Comment by ruizb** [comment]
I'm closing the issue since it has nothing to do with this library, sorry for the inconvenience!

(Great work BTW, I'm looking forward to variadic tuples being used here)

**Comment by pirix-gh** [comment]
Hey, it is possible to turn a [number, 'a' | 'b'] into a [number, 'a'] | [number, 'b'], but in most cases this would change nothing.

**Comment by ruizb** [comment]
(FYI the bug has been fixed on TypeScript, cf. https://github.com/microsoft/TypeScript/issues/39357)

**Comment by millsp** [comment]
Oh, I didn't realize this was a bug. Thanks for the update!
