### ISSUE TITLE
How to add union type to object values 

### ISSUE THREAD

**Issue by dsernst** [pirix-gh/ts-toolbelt#121]
## 🤔 Question
Given an object type like:

```ts
type Omega = { alpha: number }
```

How could I transform all of the values to also accept another type, e.g.:

```ts
type Mapped = { alpha: number | SomeType }
```

It's easy if the type is manually defined, as above.

But I'd like to make this into a transforming utility type for a library, with arbitrary objects passed in. 

E.g.

```ts
type Mapped = AcceptSomeType<{ foo: number; bar: string; baz: string[] }> 
```

is equivalent to:

```ts
type Mapped = {
  foo: number | SomeType
  bar: string | SomeType
  baz: string[] | SomeType
}
```

Is this `AcceptSomeType<T>` function possible?

Sort of like `mapValues` in Lodash. I see [O.MergeUp](https://pirix-gh.github.io/ts-toolbelt/modules/_object_mergeup_.html) can sort of do something like this, but I'm looking for it to work with any object shape passed in, not just specified keys.

(See https://github.com/nandorojo/swr-firestore/issues/21 for specific use-case)

#### Search tags, topics
#typescript #union #type #mapValues

**Comment by pirix-gh** [comment]
Hey @dsernst,

There are a few ways to do this.

- The first one is with ts-toolbelt:

```ts
import {A, O} from 'ts-toolbelt'

type O = {
    foo: number
    bar: string
    baz: string[]
}

type A = 'hello'

// Pick the solution you prefer the most
type mapped0 = O.Update<O, A.Key, A.x | 1>
type mapped1 = O.Update<O, O.Keys<O>, A.x | 1>
```

Update allows one to update existing values, or create new fields, and use the `x` placeholder (where `x` represents the original value).

- The second one is with TypeScript:

```ts
type Mapper<O extends object, A> = {
    [K in keyof O]: O[K] | A
}

type O = {
    foo: number
    bar: string
    baz: string[]
}

type A = 'hello'

type mapped0 = Mapper<O, A>
```

- But ultimately, the shortest will be:

```ts
import {O} from 'ts-toolbelt'

type O = {
    foo: number
    bar: string
    baz: string[]
}

type A = 'hello'

type mapped0 = O.Unionize<O, {[K in A.Key]: A}>
```

`Unionize` simply creates a union of the fields of 2 objects. Since our second object can have any key (`A.Key`), all the fields will get unionized. In contrast with `Update`, these last 2 solutions don't allow you choose which fields get updated. This might not be a requirement for your use-case, though.

**Comment by dsernst** [comment]
Brilliant, thank you!

You are a wizard 🧙‍♂️

**Comment by pirix-gh** [comment]
It's only my pleasure! If any help is needed on your related issue, please ask :)

**Comment by nandorojo** [comment]
@pirix-gh what if you only want it to apply to certain types of fields, for example, only to number fields?

**Comment by pirix-gh** [comment]
Hola @nandorojo,

You would do this thanks to [`SelectKeys`](https://pirix-gh.github.io/ts-toolbelt/modules/_object_selectkeys_.html)

```ts
import {A, O} from 'ts-toolbelt'

type Omega = {
    foo: number
    bar: string
    baz: string[]
} | {
    foo: 42
    bar: number
    baz: string
    qux: boolean | number
}

type SomeType = 'update'

type test0 = O.Update<
    Omega,
    O.SelectKeys<Omega, number>,
    A.x | SomeType
> // this uses 'extends->' by default

type test1 = O.Update<
    Omega,
    O.SelectKeys<Omega, number, 'contains->'>,
    A.x | SomeType
> // this makes sure the fields will contain `number`
// that is to say, fields are unions that at least contain `number`

type test2 = O.Update<
    Omega,
    O.SelectKeys<Omega, number, '<-contains'>,
    A.x | SomeType
> // this makes sure `number` will contain the fields
// that is to say, fields are unions that are only of type `number`
```
