### ISSUE TITLE
Errors due build

### ISSUE THREAD

**Issue by katedoctor** [pirix-gh/ts-toolbelt#125]
![Screen Shot 2020-07-09 at 6 47 34 PM](https://user-images.githubusercontent.com/34662518/87061647-ac0eb180-c214-11ea-93a9-36271d62b281.png)
there is some errors

**Comment by pirix-gh** [comment]
Hey @katedoctor, thanks for reporting this. Are you using ramda?

**Comment by katedoctor** [comment]
yes, I'm. I use @types/ramda as well

**Comment by pirix-gh** [comment]
Sorry about this, the fix will be out in a few minutes. Thanks :)

**Comment by katedoctor** [comment]
Thanks! Could you write here when it will be fixed?

**Comment by pirix-gh** [comment]
It's fixed! Cheers

**Comment by katedoctor** [comment]
it works! thanks^_^
