### ISSUE TITLE
about `declare module` pollution

### ISSUE THREAD

**Issue by intrnl** [pirix-gh/ts-toolbelt#126]
#### Describe your question

This isn't really a major issue, but it does raise some concern and it can be annoying to see once in a while.

I use [`react-query`](https://github.com/tannerlinsley/react-query), which is a pretty fantastic lib to use, but something I noticed is that after installing the package, I would see `ts-toolbelt`'s many type utils polluting the import suggestions.

One concern is that it declares `index` module, which is going to conflict with the actual [npm package](https://npm.im/index) of the same name.

Now I could just ignore this and move on, but honestly I couldn't be the only one to wonder, and I'm not exactly a direct user of `ts-toolbelt` either.

Is there any way to work around these, or any future plans to move away from `declare module`?

**Comment by pirix-gh** [comment]
Hey @intrnl, sorry about this. I'm busy pushing a fix that will get rid of the `index` module declaration. https://travis-ci.org/github/pirix-gh/ts-toolbelt/builds/706593110

I would like to know if you can try this again once `Deploy:master` has passed, and let me know if this is still bothering you :)

**Comment by pirix-gh** [comment]
Hey @intrnl, did this solve the problem?

**Comment by intrnl** [comment]
While that resolved the conflict with an npm package, I'm still not sure about the import pollution issue that it still has.

More and more, I feel that `declare module` should only be used for end user projects with untyped dependencies.

**Comment by pirix-gh** [comment]
I get your point, but it will stay that way until TypeScript can provide a reliable way to bundle `d.ts` files.

**Comment by pirix-gh** [comment]
https://github.com/microsoft/TypeScript/issues/4433
