### ISSUE TITLE
test should not be bundled in package

### ISSUE THREAD

**Issue by regevbr** [pirix-gh/ts-toolbelt#14]
#### Describe the bug
The `tst` directory is bundled in the npm package and it is redundant...

**Comment by regevbr** [comment]
I'll make a quick PR soon

**Comment by pirix-gh** [comment]
I've fixed it in `@next`

**Comment by regevbr** [comment]
I don't see that you changed. npmignore on the next branch

**Comment by pirix-gh** [comment]
I found out that the `.npmignore` cannot ignore for child directories, so I added to the scripts the deletion command for the `tst` folder.
