### ISSUE TITLE
Try implement recursive type fellow your way, but not work

### ISSUE THREAD

**Issue by jituanlin** [pirix-gh/ts-toolbelt#17]
Hi, Guy, I read your bog which post in medium.
And I try to improve the type of  `path` function of `Ramda`, 
but not work, I spent few hours to fix it, however...
```typescript
export type Head<T extends ReadonlyArray<any>> = T extends [any, ...any[]]
  ? T[0]
  : never;

export type Tail<T extends ReadonlyArray<any>> = ((...t: T) => any) extends ((
  _: any,
  ...tail: infer TT
) => any)
  ? TT
  : [];

export type HasTail<T extends ReadonlyArray<any>> = T extends ([] | [any])
  ? false
  : true;

export type GetByProp<P extends keyof O, O> = O[P];

export type GetByPath<
  P extends ReadonlyArray<number | string>,
  O extends object | number
> = {
  0: GetByPath<Tail<P>, GetByProp<Head<P>, O>>;
  1: GetByProp<Head<P>, O>;
}[HasTail<P> extends true ? 0 : 1];

declare const f: <
  P extends ReadonlyArray<number | string>,
  O extends object | ReadonlyArray<any>
>(
  p: P,
  o: O
) => GetByPath<P, O>;

// T is 1
type T = GetByPath<['a'],{a:1}>

// v:never
const v = f(['a'] as const, { a: 1 });
```
As you can see, the T is type `1`, and the `v` infer as `never`.
Why? Pls. Thank you.

**Comment by pirix-gh** [comment]
@jituanlin, please go read my implementation of path in `Object/Path.ts`. Your `GetByPath` seems to reference itself. These problems are quite common and this is why I brought `Iteration` types out, to move over arrays with `Next` and `Prev`.

This is what `Path` uses internally:

```ts
import {Object} from 'ts-toolbelt'

declare const f: <
  P extends readonly string[],
  O extends object
>(
  p: P,
  o: O
) => Object.Path<O, T.Writable<P>>; // the lib only accepts writable arrays

const v = f(['a', 'b', 'c'] as const, {a: {b: {c: 1}}});
```

Note that without the `as const` TS would narrow `['a', 'b', 'c']` to `string[]` and this would not work.

**Comment by jituanlin** [comment]
>  Your `GetByPath` seems to reference itself.
Yes, but I think I just follow you.
Consider bellow code you write in `Ramda`:
```typesript
    type Last<T extends any[]> = {
        0: Last<Tail<T>>;
        1: Head<T>;
    }[
        HasTail<T> extends true
        ? 0
        : 1
    ];
```
The `Last` also  reference itself, but it will well.
So, what I missing?

**Comment by pirix-gh** [comment]
The condition of your type is non-terminating in some cases. In cases where
the length of the tuple is unknown and equals number most probably.

This tutorial is for learning purposes, please use Iteration (same as
Iterator from the tutorial)

Good luck!
