### ISSUE TITLE
Add empty index.js file to out dir

### ISSUE THREAD

**Issue by rifler** [pirix-gh/ts-toolbelt#24]
Package has "main" field
https://github.com/pirix-gh/ts-toolbelt/blob/master/package.json#L26

but this file doesn't exist. I think thats why eslint triggers error `Unable to resolve path to module 'ts-toolbelt'  import/no-unresolved`.

I create this file manually by `touch ./node_modules/ts-toolbelt/out/index.js` and the error is gone

**Comment by pirix-gh** [comment]
@rifler thanks, looking into it

**Comment by pirix-gh** [comment]
Fixed
