### ISSUE TITLE
DeepReadonly for any type

### ISSUE THREAD

**Issue by xaviergonz** [pirix-gh/ts-toolbelt#25]
## 🤔 Question

I tried to look for a generic DeepReadonly in the library, but I couldn't find one, is there one?

If not, would this be a proper way to implement it?
```ts
type DeepReadonly<T> = T extends any[]
  ? T.Readonly<T, "deep"> extends infer R
    ? R
    : never
  : T extends ReadonlyArray<infer D>
  ? T.Readonly<D[], "deep"> extends infer R
    ? R
    : never
  : T extends object
  ? O.Readonly<T, keyof T, "deep"> extends infer R
    ? R
    : never
  : T
```

also, is the `extends infer R ? R : never` required here to avoid getting type instantation too deep errors?

**Comment by pirix-gh** [comment]
Hi @xaviergonz,

You can use `O.Readonly` it's generic. As `T.Readonly` just performs a `Cast` on `O.Readonly` to force TS to acknowledge that it is an Array/Tuple that we are dealing with.

**Comment by xaviergonz** [comment]
Ah thanks, so if I want it to also support primitives (by doing nothing to them) this is ok?

```ts
type DeepReadonly<T> = T extends object
  ? O.Readonly<T, keyof T, "deep"> extends infer R
    ? R
    : never
  : T
```

**Comment by pirix-gh** [comment]
Yes it's ok if you have a very specific use-case in your project

This should do:
```ts
type DeepReadonly<T> =
    T extends object
    ? O.Readonly<T, keyof T, 'deep'>
    : T
```
