### ISSUE TITLE
Pick two different branch of an object that have different subobject names

### ISSUE THREAD

**Issue by mifozski** [pirix-gh/ts-toolbelt#28]
#### Describe your question
How do I pick two different paths of an object that have different subobject names, for example:
```ts
interface Test {
  foo: {
    foofoo: string;
  };
  bar: number;
  unneeded: null;
}

type pickedTest = O.P.Pick<Test, ['foo' | 'bar', 'foofoo']>;
```

I want `pickedTest` to be
```ts
type pickedTest = {
  foo: {
    foofoo: string;
  };
  bar: number;
}
```
but the resulting type is
```ts
type pickedTest = {
  foo: {
    foofoo: string;
  };
}
```
which kinda makes sense.
What is the expected syntax here and if that's even possible?

**Comment by pirix-gh** [comment]
Hi @mifozski,

By default, it does not include something that does not have a valid path.
However, we could write another version called `PickTry` that would solve your use case:

Imagine the following scenario:

```ts
interface Test {
  foo: {
    foofoo: string;
    barbar: string
  };
  bar: {
    foofoo: {
      barbar: string
      yogyog: string
    }
  };
  unneeded: null;
}

type pickedTest = PickTry<Test, ['foo' | 'bar', 'foofoo', 'barbar']>;
```

and the ouput type would be:

```ts
type pickedTest = {
    foo: {
        foofoo: string;
    };
    bar: {
        foofoo: {
            barbar: string;
        };
    };
}
```

It it what you need? If so, do you find the name convenient (do you have a better idea)?

So the type just picks whatever it can, trying as it dives.

**Comment by pirix-gh** [comment]
Maybe I could make it the default behavior... Have to think about it.

**Comment by ctrlplusb** [comment]
Strangely enough I was trying to solve the exact some problem in my library. 😀

**Comment by pirix-gh** [comment]
@ctrlplusb what do you think? Should I make this the default behavior?

**Comment by mifozski** [comment]
I think it makes sense to make it a default behavior as I can't think of a case where we'd want to pick several paths at first and then narrow it down to something that will be valid only for one path.

**Comment by ctrlplusb** [comment]
Yep, I agree, I thought this would have been the default behaviour too. :)

**Comment by pirix-gh** [comment]
Well, thanks, closing the debate. I agree that it is inconsistent. Working on it.

**Comment by ctrlplusb** [comment]
Woot! Gonna experiment with this soon. 🎉

**Comment by pirix-gh** [comment]
I must say, this was quite a challenging type to write. I am still wondering if it could be simplified :unamused:
