### ISSUE TITLE
Examples in docs

### ISSUE THREAD

**Issue by elektronik2k5** [pirix-gh/ts-toolbelt#3]
Hello and thanks for creating this package! :bowing_man: I'm evaluating ts utility packages and this looks like a solid option, but the docs are missing examples.

#### Is your feature request related to a problem? Please describe
The docs have everything necessary, except for examples.

#### Describe the solution you'd like
Each function/type should have at least one example of how it can be used. Lodash and Ramda docs get it right, for example.

#### Describe alternatives you've considered
None. Examples are necessary to help people understand what each function/type/utility does in a clear manner. They are indispensable. 

#### Teachability, Documentation, Adoption, Migration Strategy
Examples:
- https://lodash.com/docs/#curry
- https://ramdajs.com/docs/#curry

**Comment by pirix-gh** [comment]
Don't worry, it's on the way! I was just taking a little break after the release :wink: 
I will write simple examples for all the types in such a way that it clarifies the docs.

However, I won't go too much in detail :clock1030: . 

So I'm going to open a "questions" section in the issues and will complete the docs piece by piece.

**Comment by elektronik2k5** [comment]
Cool, thanks for the thorough work and commitment!

**Comment by pirix-gh** [comment]
I will work on the documentation right after the official release of the v3. 

Sorry for the delays!

**Comment by pirix-gh** [comment]
I don't have the time to write examples for all the types... Sorry about that. But I am willing to complete them progressively as users ask for it. So I updated the Readme, where I invite users to ask for examples now. It's progressive, and works the same way as the wiki.

The amount of work is too huge... But rest assured, I will reply fast & update the docs fast as well.
This way is more maintainable, as I plan to release more projects (that will work the same way).

I will also write examples whenever I use a type on my other projects. And hopefully, one day, we will get to the end of it!
