### ISSUE TITLE
Add a RequireOnlyOne object type 

### ISSUE THREAD

**Issue by regevbr** [pirix-gh/ts-toolbelt#32]
#### Describe the solution you'd like
It will be a really nice addition to add a `require only one` Object type.
The basic idea behind it is that given an Object with multiple keys, create a union type in a way that a sub set of keys from the object can only exists on its own with out the others.
E.G
```typescript
interface I {
    y: number;
    x1: string;
    x2: number;
}
type IUnion = RequireOnlyOne<I, 'x1' | 'x2'>;
/*
{
    y: number;
    x1: string;
} | 
{
    y: number;
    x2: number;
}
*/
```

I currently achieve that type using the following:
```typescript
type RequireOnlyOne<T, Keys extends keyof T = keyof T> =
    Pick<T, Exclude<keyof T, Keys>>
    & {
    [K in Keys]-?:
    Required<Pick<T, K>>
    & Partial<Record<Exclude<Keys, K>, undefined>>
}[Keys];
```

@pirix-gh what do you think?

**Comment by tonivj5** [comment]
I was just looking for it yesterday :laughing: :+1:

**Comment by pirix-gh** [comment]
Hi @regevbr, glad to see you,

Yes we can add such a type. I just have a few questions:
- Is it voluntary to make the fields also optional?
```ts
// This is what I got from your code
type IUnion = {
    y: number;
    x1: string;
    x2?: undefined; // I can make this disappear if needed
} | {
    y: number;
    x2: number;
    x1?: undefined; // I can make this disappear if needed
}
```
- Can you give me one or two use-cases? I never came across such scenario.
- Is it to say, I either want this part or that part of an object?

**Comment by pirix-gh** [comment]
@tonivj5 @regevbr 

Here is a version that preserves the type modifiers (readonly, ? ...). Don't hesitate to use `Compute` if your types don't render properly, it forces them to render to something we can read. So here's my implementation:

```ts
import {Index} from '../_Internal'
import {Omit} from './Omit'
import {Pick} from './Pick'
import {Compute} from '../Any/Compute'

interface I {
    a: 'a';
    b?: 'b';
    c?: 'c';
    d?: 'd';
}

type IUnion = EitherWith<I, 'b' | 'c' | 'd'>;

type EitherWith<O extends object, K extends Index> =
    Compute<Omit<O, K> & {   // Merge all but K
        [P in K]: Pick<O, P> // With K possibilities
    }[K]>
/*
type IUnion = {
    a: "a";
    b?: "b" | undefined;
} | {
    a: "a";
    c?: "c" | undefined;
} | {
    a: "a";
    d?: "d" | undefined;
}
*/
```

**Comment by pirix-gh** [comment]
Hey @regevbr, I will include this type if we can agree to a more general use case (and put words on it).

I am not fond of the `undefined` as it is because also "other properties can't be used" if they're not present (in my implementation). Maybe it's just related to your project, so you should write your own type since this lib is a general-purpose tool.

And we need too make sure that the modifiers are preserved, since it **has to** be for general purpose.

Those are my prerequisites for including this type. I need to know more about clear use-cases that can serve multiple scenarios.

**Comment by regevbr** [comment]
If I use your implementation in my library, the behavior is very strange.
The computed type for `expression` in https://github.com/regevbr/json-expression-eval/blob/8086845092722cb100dbd41304a983338fe65afa/src/example/example.ts#L17 is:
```typescript
type x = {
        not: Expression<ExpressionContext, {
            user: (user: string, context: { userId: string; }) => boolean;
            maxCount: (maxCount: number, context: { times: number; }) => boolean;
        }>;
    }
    |
    {
        or: Expression<ExpressionContext, {
            user: (user: string, context: { userId: string; }) => boolean;
            maxCount: (maxCount: number, context: { times: number; }) => boolean;
        }>
        [];
    }
    |
    {
        and: Expression<ExpressionContext, {
            user: (user: string, context: { userId: string; }) => boolean;
            maxCount: (maxCount: number, context: { times: number; }) => boolean;
        }>
        [];
    }
    |
    {
        user: string;
    }
    |
    {
        userId: string | EqualCompareOp<ExpressionContext, "userId"> | NotEqualCompareOp<ExpressionContext, "userId"> | GtCompareOp<ExpressionContext, "userId"> | GteCompareOp<ExpressionContext, "userId"> | LtCompareOp<ExpressionContext, "userId"> | LteCompareOp<ExpressionContext, "userId">;
    }
    |
    {
        times: number | EqualCompareOp<ExpressionContext, "times"> | NotEqualCompareOp<ExpressionContext, "times"> | GtCompareOp<ExpressionContext, "times"> | GteCompareOp<ExpressionContext, "times"> | LtCompareOp<ExpressionContext, "times"> | LteCompareOp<ExpressionContext, "times">;
    }
    |
    {
        maxCount: number;
    }

```

But it is still valid to set it like:
```typescript
let expression: Expression<ExpressionContext, ExpressionFunction> = {
    user: 'a@b.com',
    times: 3,
};
```
Can you explain it?

The reason my library only allows a single property is the fact that in every object "level" there can only by a single operand, and I can only discover that operand by computing the singe key the "level" has and evaluate it. If you pass more than 1 argument to a level, it will fail at run time which is undesired.

**Comment by regevbr** [comment]
@tonivj5 maybe you can shed some light on your use case?

**Comment by pirix-gh** [comment]
@regevbr OOOooh I see now. This is kind of strange. I understand your problem now.

**Comment by pirix-gh** [comment]
It's a bug https://github.com/Microsoft/TypeScript/issues/20863

**Comment by regevbr** [comment]
@pirix-gh indeed seems like it, and the workaround suggested there is an extended form of my solution. How should we proceed?

**Comment by pirix-gh** [comment]
Hola @regevbr @tonivj5

You guys can now use [Either](https://github.com/pirix-gh/ts-toolbelt/blob/740742c0/src/Object/Either.ts#L16)

**Comment by pirix-gh** [comment]
I hope this ts issue will resolve one day

**Comment by regevbr** [comment]
@pirix-gh you are the best! Will get to check it right away

**Comment by regevbr** [comment]
@pirix-gh sadly it doesn't work :-( as I mentioned earlier here, the usage of Compute causes issues.

I found an example that does't work, but not sure that is why it doesn't work for me:

```typescript
interface I2 {
    f: string;
}

interface I {
    a: 'a';
    b?: 'b';
    c?: 'c';
    d?: 'd';
}

type IUnion = tObject.Either<I | I2, 'b' | 'c' | 'd'>; // resolved to {}
```

If you want to see the errors I get, best that you checkout my library as change in index.ts the `RequireOnlyOne` type to
```
export type RequireOnlyOne<T extends object> = Any.Compute<Object.Either<T, keyof T>>;
```

**Comment by regevbr** [comment]
If I remove the Compure part from Strict, it works nicely for me, no idea why it matters so much...

**Comment by pirix-gh** [comment]
Ah, let me check this out. `Compute` is strictly for the user readability.

**Comment by pirix-gh** [comment]
@regevbr, the problem was coming from `Compute` that was too strict, then your type did not even resolve to any. I've changed it for the looser implementation from Titian. I've pushed out a fix. Sorry 'bout that!

**Comment by regevbr** [comment]
@pirix-gh cool works now! Again thanks a lot :-)

**Comment by pirix-gh** [comment]
Somehow you always bring to me the worst issues :rofl: 
Just joking, thanks, I really appreciate your help @regevbr

**Comment by regevbr** [comment]
@pirix-gh haha, I just work with very complex typings :-)
