### ISSUE TITLE
add type for callback

### ISSUE THREAD

**Issue by regevbr** [pirix-gh/ts-toolbelt#34]
#### Describe the solution you'd like
Callback are sadly still very common, no reason why we should not type it properly :-)
```typescript
type Callback<T> = ((error: Error, result?: never) => void) & ((error: undefined | null, result: T) => void);

function callback(error: undefined | null, result: string): void;
function callback(error: Error, result?: never): void;
function callback(error: Error | undefined | null, result?: string): void {
  return;
}

function f(cb: Callback<string>): void {
  cb(new Error('a'));
  cb(undefined, 'd');
  cb(new Error('a'), 's'); // produces error
  cb(undefined); // produces error
}
f(callback);
```

@pirix-gh thoughts?

**Comment by pirix-gh** [comment]
@regevbr I think that this is really dependent on the taste of the developer... There is many other callback flavors, so I cannot add this, sorry.
I believe that all of these project-specific {types, constants, tools} belong inside a `Util.ts` at the root of the project's folder and that module-specific {types, constants, tools} belong in a static `class Util` at the bottom of the module file. Well, that's (just) how I organize and sort all the non-generic bits and pieces that I need to write. But this project's goal isn't about being opinionated, but rather to be generic.

**Comment by regevbr** [comment]
I completely understand, but as I have 10's of projects (most are private) I find myself writing those kind of types over and over again. More over, I don't believe there is an opinion here (maybe just the `Error` type which we can generfiy) as callback structure is an industry wide convention and not something developers play with (at least in most use cases, as I have seen some rare conventions of 3 arguments to the callback).
In any case, thanks for taking it under consideration!

**Comment by pirix-gh** [comment]
I've seen many devs using callbacks without error handling, or where they rather throw errors, not handling it in a functional manner like you do (but with try/catch). It's about different tastes. In my opinion, I prefer the (simple) functional approach, as it does the error reporting deeply and without the awful try/catch everywhere (thanks Java!) and that can be achieved with the technique you've shown or an `either` monad for instance. I personally don't care about the standards as there is many ways to achieve one thing when it comes to programming.

And for your projects, I understand the need to share stuff around. Maybe you could create a monorepo? I find it overkill for most projects, I have a liking for separating stuff. For instance, on my projects, I have a package that I use just to share all my (common) devDependencies. You could as well create a local package (no need to publish if you have a bundler (eg. webpack)), pack it with `npm pack` and install it on your local packages. Or you could as well publish it?

**Comment by regevbr** [comment]
Ok got your point!

As to handling common stuff:
I have a private npm repo with a published common package that everyone depends on. I also don't believe in the monorepo way - all my micro services and packages are sitting in individual projects - easier to manage dependencies in ci/cd flows.
