### ISSUE TITLE
extract keys of type (key type, not its field type)

### ISSUE THREAD

**Issue by regevbr** [pirix-gh/ts-toolbelt#35]
#### Describe the solution you'd like
Since keys of an object can be of type `string|number|symbol` and sometimes types require only string values, it will be handy to have a type that extracts only the string key (or of any type for that matter)

```typescript
type Index = string | number | symbol; // I think we should make that type public!

type KeysOfType<T extends object, M extends Index> = Extract<keyof T, M>;

type t = KeysOfType<{
  a: number;
  2: number;
}, string>; // "a"
```

@pirix-gh thoughts?

**Comment by pirix-gh** [comment]
@regevbr , I currently achieve this by doing `[keys] & [type]`. For example:
```ts
('1' | 1) & string // '1'
```

**Comment by regevbr** [comment]
That makes sense, although less intuitive in my view. Thought this type will make it more _verbose_ and easier to discover in your library

**Comment by pirix-gh** [comment]
You can still be verbose (but more generic) with https://pirix-gh.github.io/ts-toolbelt/modules/_union_filter_.html#filter

**Comment by pirix-gh** [comment]
Sorry @regevbr, I meant https://pirix-gh.github.io/ts-toolbelt/modules/_union_select_.html#select

**Comment by regevbr** [comment]
@pirix-gh do you think we can at least expose 
```typescript
type Index = string | number | symbol;
```
in the public interface?

**Comment by pirix-gh** [comment]
@regevbr Yes, I also found myself needing it a few times
