### ISSUE TITLE
add assertUnreachable method (not type...)

### ISSUE THREAD

**Issue by regevbr** [pirix-gh/ts-toolbelt#36]
#### Describe the solution you'd like
When using switch on types, typescript allows a validation to make sure you covered all the cases in the form of a method that accepts never:

```typescript
const assertUnreachable = (x: never): never => {
  throw new Error(`Didn't expect to get here`);
};
```

So the following will work:
```typescript
type T1 = 'a' | 'b';
const f = (v: T1): void => {
  switch (v) {
    case 'a':
      console.log('a');
      break;
    case 'b':
      console.log('b');
      break;
    default:
      assertUnreachable(v);
  }
};
```

But if we change `T1` to 
```typescript
type T1 = 'a' | 'b' | 'c';
```
TS will produce an error. Letting you know you forgot to cover a case.

I know this is not a type, but it is a very handy method that can be widely reused.

@pirix-gh what do you say? If you want to throw it down the stairs I will completely understand :-)

**Comment by pirix-gh** [comment]
Yes, I is not type-level, so I can't add it. I think this would belong in a utility library.
