### ISSUE TITLE
TS2315: Type '_Omit' is not generic and TS2456: Type alias '_Omit' circularly references itself.

### ISSUE THREAD

**Issue by Sieabah** [pirix-gh/ts-toolbelt#37]
#### Describe the bug
```
node_modules/ts-toolbelt/out/types/src/Object/P/Omit.d.ts(12,14): error TS2456: Type alias '_Omit' circularly references itself.
node_modules/ts-toolbelt/out/types/src/Object/P/Omit.d.ts(13,91): error TS2315: Type '_Omit' is not generic.
node_modules/ts-toolbelt/out/types/src/Object/P/Omit.d.ts(23,66): error TS2315: Type '_Omit' is not generic.
```

#### Reproduce the bug
Typescript: 3.4.3

#### Expected behavior
Prevents compilation

**Comment by pirix-gh** [comment]
@Sieabah It's in the readme, only TS >= 3.5 :laughing: But don't worry, you're not the only one!

**Comment by Sieabah** [comment]
Oops! Sorry, I recently only found this because of upgrading ramda and this suddenly popped up, will try to upgrade my TS and see if it doesn't break anything else!
