### ISSUE TITLE
Build is broken in >3.8.19

### ISSUE THREAD

**Issue by tonivj5** [pirix-gh/ts-toolbelt#42]
#### Describe the bug
Hi :smile_cat:! I have updated the lib to the latest and webpack is showing an error :cry: 

In <3.8.19
![image](https://user-images.githubusercontent.com/7110786/63793219-8419a680-c8ff-11e9-899d-3e5bcdda757c.png)

In >3.8.19
![image](https://user-images.githubusercontent.com/7110786/63793282-add2cd80-c8ff-11e9-8879-5c878d145a9e.png)

I have installed some other versions to confirm it, after 3.8.19 release, all onwards are broken.

It produces an error because webpack (and I suppose other bundlers) use main entry from package.json
![image](https://user-images.githubusercontent.com/7110786/63793452-fe4a2b00-c8ff-11e9-946c-234af54365a5.png)
![image](https://user-images.githubusercontent.com/7110786/63793469-0b671a00-c900-11e9-80bd-2dc2753ccb90.png)

#### Expected behavior
Not fail

#### Possible Solution
Get index.js back in `out` folder?

**Comment by pirix-gh** [comment]
Hey @tonivj5, thanks for reporting this!

This probably happened while migrating my release to Travis

Will fix this right away,

Cheers

**Comment by pirix-gh** [comment]
@tonivj5 it's resolved manually, for now. It's an issue with Travis that needs more investigation.

**Comment by tonivj5** [comment]
Just I have installed 3.8.59 and I have seen that index.js came back :tada:. Thank you very much for your efforts. You're fast, boy :laughing::100:
