### ISSUE TITLE
Correct type of currying

### ISSUE THREAD

**Issue by dmfilipenko** [pirix-gh/ts-toolbelt#43]
#### Describe your question
I've stuck with `React`, `Typescript`, and `Ramda`. I can't add a correct type for currying. Seems like ramda use underhood `ts-toolbelt` to add typing for a currying.
```
I've got an error with isElementIcon(refIcon)
const isElementIcon: <[React.RefObject<HTMLDivElement>]>(args_0: React.RefObject<HTMLDivElement>) => Curry<(target: EventTargetOrNull) => boolean>
Type 'Curry<(target: EventTargetOrNull) => boolean>' is not assignable to type 'SafePred<EventTargetOrNull>'.
  Types of parameters 'target' and 'a' are incompatible.
    Type 'EventTargetOrNull' is not assignable to type 'Node | EventTarget | Type<"x", "x">'.
      Type 'null' is not assignable to type 'Node | EventTarget | Type<"x", "x">'.ts(2322)
```
```typescript
type EventTargetOrNull = Node | EventTarget | null
const [isOpen, setIsOpen] = useState(false)
const refIcon = useRef<HTMLDivElement>(null)

const isElementIcon = curry<(ref: RefObject<HTMLDivElement>, target: EventTargetOrNull) => boolean>((ref, target) => {
  return ref.current !== null && (ref.current === target || ref.current.contains((target as unknown) as Node))
})


const handleClick = pipe<MouseEvent | TouchEvent, EventTargetOrNull, void>(
  prop('target'),
  cond<EventTargetOrNull, void>([
    [isElementIcon(refIcon), () => setIsOpen(!isOpen)],
    [isOutsideWrapperEvent(refWrapper), hideTooltip]
  ])
)
```

**Comment by pirix-gh** [comment]
Hi @dmfilipenko, can you give me a smaller reproduction of the bug for me to copy-paste it?

Then, I'll look into it :smiley:

**Comment by dmfilipenko** [comment]
@pirix-gh yeap, sorry. Here is a reduced example
```typescript
const isGreater = curry((one: number, two: number): boolean => {
  return one < two
})

const check = cond<number, void>([
  [isGreater(1), () => ({})]
])
```
got this 
```typescript
const isGreater: <[1]>(args_0: 1) => Curry<(two: number) => boolean>
Type 'Curry<(two: number) => boolean>' is not assignable to type 'SafePred<number>'.
  Type 'Curry<(two: number) => boolean>' is not assignable to type 'boolean'.
```

**Comment by pirix-gh** [comment]
Sorry, I actually meant a self-contained example. In yours I don't know what `cond` does and I also don't have access to `SafePred`... Make it simple please, when reporting bugs, as we, maintainers, don't always have the time to make your specific code work. Open a new file and try to reproduce the bug independently from your source. Thanks

**Comment by dmfilipenko** [comment]
@pirix-gh https://github.com/dmfilipenko/curry/ is this enough?

**Comment by pirix-gh** [comment]
Hey @dmfilipenko, it's been fixed. Thanks for reporting this bug.

_PS: Remove & re-install ramda_

**Comment by dmfilipenko** [comment]
It doesnt help still have 
`ts-toolbelt`
`
"version": "3.8.63",
`

**Comment by pirix-gh** [comment]
Yes, sorry @dmfilipenko for the misinformation. I submitted a PR to update the version on DefinitelyTyped a few days ago, you'll just have to wait for it to be merged.

**Comment by pirix-gh** [comment]
@dmfilipenko, it did update correctly. It seems like there was delays with the publication of the package.
That interruption could have been caused either by npm or the types-publisher. Back to normal.

**Comment by dmfilipenko** [comment]
@pirix-gh 🙏thank you
