### ISSUE TITLE
Patch version is not incremental 

### ISSUE THREAD

**Issue by song888k** [pirix-gh/ts-toolbelt#44]
#### Describe the bug
I am using Microsoft DevOps Feed and reference npmjs as an upstream package source. When I try to "npm install ts-toolbelt", I got following errors:

> {"success":"false","error":"BadGateway","reason":"Error encountered fetching upstream data. A configured upstream registry failed: {Name = npmjs, Location = https://registry.npmjs.org/, Protocol = npm, UpstreamSourceType = Public ExceptionType = Microsoft.VisualStudio.Services.Packaging.ServiceShared.Versioning.InvalidSemanticVersionException, ExceptionMessage = The version 3.8.1567781323189 is invalid.}"}

Not for sure (I am checking with Microsoft support) but I guess the reason for this problem is that the patch version is not incremental strictly:
- 3.8.70 
- 3.8.1567788970295
- 3.8.1567788972460
- 3.8.69

70 < 1567788970295 < 1567788972460 > 69

Here is the [Semantic Versioning Spec](https://semver.org/).

Could you help unpublish the version numbers that are not incremented?

**Comment by pirix-gh** [comment]
Oops, I missed a part of the version, I don't know how npm let this go through in the first place.

Thanks for reporting this @song888k so early, I can easily unpublish it now.

**Comment by pirix-gh** [comment]
@song888k I did unpublish the packages but they are still visible on the npm package. So I am not sure if they we're unpublished correctly, and I'll have to contact npm.

Would you mind trying to install again and let me know if it works or not?

**Comment by song888k** [comment]
Thank you for the quick action, @pirix-gh! But it still doesn't work. My guess is that unless those bad versions disappear from the response of https://registry.npmjs.org/ts-toolbelt, the problem will still exist.

**Comment by pirix-gh** [comment]
Pleasure! I sent a request (email) to npm for them to delete these packages. I'll notify you when it's done :)

**Comment by pirix-gh** [comment]
I'm not sure this will ever get fixed. I sent 3 emails to npm, without a single reply -- what an deligthful customer experience.

**Comment by pirix-gh** [comment]
This should be fix
