### ISSUE TITLE
Why is `<x> extends infer X ? <y>: never` so used in the codebase?

### ISSUE THREAD

**Issue by pirix-gh** [pirix-gh/ts-toolbelt#5]

**Comment by pirix-gh** [comment]
I use this syntax to defer the evaluation of a type... Otherwise TS evaluates all the types in their full depth. This causes performance issues and is irrelevant because we only want to compute when we've received the type parameters. As a result, the ts-toolbelt types load fast.

But it is not the only use case. Like I said above, TS can complain that a type is too deep to compute, then you can force it to compute step by step. So I especially use this on recursive types (which are much deeper because they're recursive).

And one last reason is that it resets the type nesting count. TS also prevents to nest too many types, and throws errors when we do so. But since one of the goals of this lib is to combine types together, it is wise to reset that depth count (that is increased by the utility type itself).

In some cases it might not be wise to do this, as it can make TS swallow warnings. And this is the reason why ts-toolbelt is thoroughly tested and all the types are benchmarked (by me by hand, for now).

**Comment by ekilah** [comment]
Can you add an example of real code from this project that does this to this wiki entry? It's hard to understand if/how `x` and `X` are related in your pseudocode `<x> extends infer X ? <y>: never`.

**Comment by pirix-gh** [comment]
You can check this [example out](https://github.com/pirix-gh/ts-toolbelt/blob/0182a00/src/Object/Assign.ts)
