### ISSUE TITLE
O.Writable doesn't work well with generics after update to 4.0.10

### ISSUE THREAD

**Issue by xaviergonz** [pirix-gh/ts-toolbelt#50]
```
class M {
  fn(): void {}
  x = 5
}

function f<T extends M>(m: T) {
    const w = m as O.Writable<T>
    w.fn() // complains fn is not there
    w.x = 10 // complains x is not there
}
```
works ok with the latest version of 3

**Comment by xaviergonz** [comment]
not sure if related to the old https://github.com/pirix-gh/ts-toolbelt/issues/41

**Comment by pirix-gh** [comment]
Ping @xaviergonz. I've just fixed it, it was not related to #41, but related to the refactor of 4.0.
This happened when I brought out true type distribution. Not sure why, though, but it seems like type distribution (`X extends unknown`) can break a deferred generic evaluation, and evaluate it immediately instead.

Please do not hesitate to open a bug, or a question if you see anything else!

Cheers

**Comment by pirix-gh** [comment]
Build is not passing, let me fix this

**Comment by pirix-gh** [comment]
It's out

**Comment by xaviergonz** [comment]
Thanks! Will check it out later

**Comment by xaviergonz** [comment]
Hmm, I don't see a new version

**Comment by pirix-gh** [comment]
Sorry, about this. Got a false positive with the CI. It's out (for real)
