### ISSUE TITLE
Broken compilation when using es2019 lib

### ISSUE THREAD

**Issue by vogre** [pirix-gh/ts-toolbelt#58]
#### Describe the bug
Installing `ts-toobelt` v4.7.19 when using lib `esnext` or `es2019` causes compilation error in
```
node_modules/ts-toolbelt/out/types/src/Tuple/Diff.d.ts:17:96 - error TS2589: Type instantiation is excessively deep and possibly infinite.

17 export declare type Diff<T extends Tuple, T1 extends Tuple, match extends Match = 'default'> = TupleOf<ODiff<ObjectOf<T>, ObjectOf<T1>, match>>;
```

Installing v4.7.18 does not cause this error

#### Reproduce the bug
Use this minimal `tsconfig.json`

```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "lib": ["es2019"],
    "strict": true
  }
}
```

#### Additional context
TypeScript 3.6.3

Only `es2019.array` is enough to trigger the error, although not clear what in https://github.com/microsoft/TypeScript/blob/master/lib/lib.es2019.array.d.ts causes it.

**Comment by pirix-gh** [comment]
Hi @vogre, thanks for reporting this issue. Looking into it

**Comment by pirix-gh** [comment]
It's fixed!
