### ISSUE TITLE
Type inference not working with F.Curry and generic function

### ISSUE THREAD

**Issue by ruizb** [pirix-gh/ts-toolbelt#59]
#### Describe your question
Hello, it seems that I have a wrong type inference with typescript@3.6 and ts-toolbelt@4.8 when using the following:

```ts
const append = curry(<A>(item: A, list: A[]) => list.concat([item]))
const appendA = append('a')
// type is `(list: unknown[]) => unknown[]` instead of `(list: string[]) => string[]`
// type could also look like `(list: {}[]) => {}[]` depending on TS and/or IDE...
```

I made a small project on codesandbox.io so you can check by yourselves: [click here to see it](https://codesandbox.io/s/priceless-glade-3f5d4?fontsize=14&module=%2Fsrc%2Findex.ts&view=editor).

Is type inference supposed to work with F.Curry and generic functions?

#### Search tags, topics
#typescript #curry #toolbelt #generic #function #parametrized #type #inference #not #working

**Comment by pirix-gh** [comment]
Hi @ruizb, this is a TypeScript limitation that I explained in response to a similar comment in https://github.com/microsoft/TypeScript/issues/5453#issuecomment-478328124

So I'll close the issue now, but rest assured that this feature will land as soon as it became possible.

Cheers
