### ISSUE TITLE
TypeScript 3.6.4 incompatible

### ISSUE THREAD

**Issue by qwelias** [pirix-gh/ts-toolbelt#68]
`ts-toolbelt@4.9.30`
```
node_modules/ts-toolbelt/out/types/src/Tuple/Reverse.d.ts:15:14 - error TS2589: Type instantiation is excessively deep and possibly infinite.

15 declare type _Reverse<T extends Tuple, TO extends Tuple = [], L extends Number = Max<Length<T, 's'>>, I extends Iteration = IterationOf<'0'>> = {
                ~~~~~~~~

node_modules/ts-toolbelt/out/types/src/Tuple/Reverse.d.ts:27:71 - error TS2589: Type instantiation is excessively deep and possibly infinite.

27 export declare type Reverse<T extends Tuple, TO extends Tuple = []> = _Reverse<T, TO> extends infer X ? Cast<X, Tuple> : never;
                                                                         ~~~~~~~~~~~~~~~

```

**Comment by eyexpo-thomas** [comment]
`npm list ts-toolbelt` will show you which package is importing ts-toolbelt so you can deal with it.

**Comment by pirix-gh** [comment]
Hi @qwelias, thanks for reporting this. Investigating it.

**Comment by pirix-gh** [comment]
Hi @qwelias @eyexpo-thomas, thanks for reporting this.

This seems to be only related to 3.6.4 only.

I'm going to make sure this does not happen again by testing each single version of TS that is supported before the release (with the CI).

**Comment by pirix-gh** [comment]
Fixed, it'll be out in a few minutes. https://travis-ci.org/pirix-gh/ts-toolbelt/builds/606383083
