### ISSUE TITLE
Clean/Ensure type instantiation is infinitely deep when using an index signature

### ISSUE THREAD

**Issue by vogre** [pirix-gh/ts-toolbelt#74]
#### Describe the bug
Encountered when trying to use `ramda` `merge(a: { [key: string]: string }, b)`.

#### Reproduce the bug
```ts
import { O } from 'ts-toolbelt';
const r: O.Ensure<{ [key: string]: string }> = { a: 'hey' };
```

#### Additional context
Happened in `ts-toolbelt` v4.12.11

**Comment by pirix-gh** [comment]
Hi @vogre, really sorry about this. The fix is out in a few minutes!

https://travis-ci.org/pirix-gh/ts-toolbelt/builds/620057580

So you can just reinstall ramda and the bug should be gone.
