### ISSUE TITLE
No index.js file so eslint complaining it cannot resolve the import

### ISSUE THREAD

**Issue by dylanaubrey** [pirix-gh/ts-toolbelt#8]
#### Describe the bug

In the lib's `package.json` the `main` field points to a `index.js` file that does not exist when the lib is installed in a project. Because of this, in the project, eslint complains it cannot resolve the import.

#### Expected behavior
The lib should have an `index.js` file, even if it is empty, so that linters and other intellisense tools can find the file which they are directed to by the `package.json` `main` field.

**Comment by ErDmKo** [comment]
I still can't to use linter. index.js is missing.
https://www.jsdelivr.com/package/npm/ts-toolbelt?path=out

**Comment by pirix-gh** [comment]
Sorry, I rolled back by mistake. Will merge soon
