### ISSUE TITLE
expression is not callable when using O.Writable

### ISSUE THREAD

**Issue by xaviergonz** [pirix-gh/ts-toolbelt#84]
Worked ok in 4.x, doesn't work in 6.x
TS 3.7.4

```ts
class X {
  fn(): void {}
}

function test<C extends X>(c: C) {
  const cc = c as O.Writable<C>
  cc.fn() // this expression is not callable
}
```

**Comment by pirix-gh** [comment]
Hi @xaviergonz, thanks for reporting his. I'm going to push a fix soon.

**Comment by pirix-gh** [comment]
Hold on, it's out in a few minutes! https://travis-ci.org/pirix-gh/ts-toolbelt/builds/631255536?utm_source=github_status&utm_medium=notification

Cheers

**Comment by xaviergonz** [comment]
That was fast, thanks!

**Comment by pirix-gh** [comment]
Like Speedy Gonzales :mouse::dash:
