### ISSUE TITLE
Get union of enum values

### ISSUE THREAD

**Issue by sanex3339** [pirix-gh/ts-toolbelt#85]
#### Describe your question
Hi. Here is any way to get union of enum values?
Tried many things, none of them is worked

**Comment by pirix-gh** [comment]
Hi @sanex3339, the `enum` itself kind of works like a union:

```ts
enum E {
    A,
    B,
    C,
    D,
    X,
}

type test0 = Exclude<E, 0> // E.B | E.C | E.D | E.X
```

https://www.typescriptlang.org/docs/handbook/enums.html

Did this solve your problem?

**Comment by sanex3339** [comment]
I'm want something different.
```
enum SomeOptionValue {
   Bar = 'bar',
   Baz = 'baz
}

type Options = {
    someOption: EnumValues<SomeOptionValue> // 'bar' | 'baz', not 'SomeOptionValue.Bar | SomeOptionValue.Baz'
};
```

**Comment by pirix-gh** [comment]
It's a reference, you can't change it/do that.

**Comment by pirix-gh** [comment]
You should try to replace your enum with plain objects, make a helper library if you really need this.
