### ISSUE TITLE
function parameter name inference with UnNest

### ISSUE THREAD

**Issue by tao-cumplido** [pirix-gh/ts-toolbelt#87]
## 🤔 Question

```ts
import { L } from 'ts-toolbelt';

type A = (a1: string) => void;
type B = (b1: number, b2: string) => void;
type C = (c1: boolean, c2: string) => void;

type X = (...args: L.UnNest<[Parameters<A>, Parameters<B>, Parameters<C>]>) => void;
```

I have no idea how typescript handles parameter names at all, but in the above example `X` is inferred to `(head: string, head: number, head: string, c1: boolean, c2: string) => void`. So apparently only the parameters names of the last function are preserved.

Do you know if it would be possible to preserve all the parameter names?

Other solutions I tried didn't preserve any parameter names at all.

**Comment by pirix-gh** [comment]
Hi @tao-cumplido, no it is not possible to preserve the names, unfortunately. This is a typescript limitation. But this is what you could do:

```ts
import { L } from 'ts-toolbelt';

type A = (a1: string) => void;
type B = (b1: number, b2: string) => void;
type C = (c1: boolean, c2: string) => void;
type P = L.UnNest<[Parameters<A>, Parameters<B>, Parameters<C>]>

type X = (a1: P[0], b1: P[1], b2: P[2], c1: P[3], c2: P[4]) => void;
```
