### ISSUE TITLE
Use Object.Merge with unlimited arguments

### ISSUE THREAD

**Issue by mesqueeb** [pirix-gh/ts-toolbelt#90]
## 🤔 Question

Hi @pirix-gh,
Thanks so much for providing this library! What a cool one.

#### Describe your question

I have a question about merging multiple objects deeply.

## The Question:
> Do you have any advice to me how I can perhaps use your `Object.merge` with unlimited arguments?

## The background:

For you to understand my clear question, I need to give you some background on what I got so far:

First, I made a function that can deep-merge objects like so:
```ts
type plainObject = {[key: string]: any}

function merge<T1 extends plainObject, T2 extends plainObject>(oneObject: T1, anotherObject: T2): T1 & T2 {
  // my implementation
}
```

In some cases just a simple Union like T1 & T2 didn't work nicely, so I tried your library and it works much better:

```ts
type plainObject = {[key: string]: any}

function merge<T1 extends plainObject, T2 extends plainObject>(oneObject: T1, anotherObject: T2): Object.Merge<T1, T2, 'deep'> {
  // my implementation
}
```

However, I need to update my function to be able to receive any amount of params.
I finished my implementation and it looks something like this:
```ts
function merge<T extends plainObject, Tn extends plainObject[]>(oneObject: T, ...otherObjects: Tn) {
  // my implementation
}
```

Then after some googling I found [a Japanese article](https://www.kabuku.co.jp/developers/typescript-object-assign) on how to write the return type for this and I found this:

```ts
type Assigned<T, U extends any[]> = {
  0: T
  1: ((...t: U) => any) extends (head: infer Head, ...tail: infer Tail) => any
    ? Assigned<Omit<T, keyof Head> & Head, Tail>
    : never
}[U['length'] extends 0 ? 0 : 1]
```

I applied it like so:
```ts
function merge<T extends plainObject, Tn extends plainObject[]>(oneObject: T, ...otherObjects: Tn): Assigned<T, Tn> {
  // my implementation
}
```

And this "kind of" works, but still gives me errors for deep objects etc.

Do you have any advice to me how I can perhaps use your `Object.merge` with unlimited arguments?

Best regards!

#### Search tags, topics

#typescript #merge #arguments #object.assign

**Comment by mesqueeb** [comment]
This is what I came up with.
Still needs more testing, but I thought I'd let you know:

```ts
type PlainObject = { [key: string | symbol]: any }

type IsPlainObject<T> = T extends PlainObject ? true : false

type Assign<T1, T2> = [IsPlainObject<T1>, IsPlainObject<T2>] extends [true, true] ? T1 & T2 : T2

type Merged<T, U extends any[]> = {
  0: T
  1: ((...t: U) => any) extends (head: infer Head, ...tail: infer Tail) => any
    ? Merged<Assign<T, Head>, Tail>
    : never
}[U['length'] extends 0 ? 0 : 1]
```

I use it like so:
```ts
function merge<T extends plainObject, Tn extends plainObject[]>(oneObject: T, ...otherObjects: Tn): Merged<T, Tn> {
  // my implementation
}
```

**Comment by mesqueeb** [comment]
@pirix-gh I wanted to give another update.
I tried with your `Object.Assign` function, but this doesn't seem to do deep assigns.
```ts
export function merge<T extends PlainObject, Tn extends PlainObject[]> (
  origin: T,
  ...newComers: Tn
): ObjectTs.Assign<T, Tn> {
  // my implementation
}
```
gives me this shallow merged type:
<img width="334" alt="image" src="https://user-images.githubusercontent.com/3253920/74312101-55f82800-4db4-11ea-8956-915ee21cc075.png">

**Comment by mesqueeb** [comment]
@pirix-gh are you able to help me with this problem? 😅

**Comment by pirix-gh** [comment]
Yes, sure. You can use this version in your project:

You got that error because you did not specify the sub-type of `T1` & `T2`. In my code below, I used `O extends object`.

```ts
import {Iteration} from '../Iteration/Iteration'
import {IterationOf} from '../Iteration/IterationOf'
import {MergeFlat, MergeDeep} from './Merge'
import {Pos} from '../Iteration/Pos'
import {Next} from '../Iteration/Next'
import {Length} from '../List/Length'
import {Cast} from '../Any/Cast'
import {List} from '../List/List'
import {Extends} from '../Any/Extends'

/**
@hidden
*/
type __AssignDeep<O extends object, Os extends List<object>, I extends Iteration = IterationOf<'0'>> = {
    0: __AssignDeep<MergeDeep<Os[Pos<I>], O>, Os, Next<I>>
    1: O
}[Extends<Pos<I>, Length<Os>>]

/**
@hidden
*/
export type _AssignDeep<O extends object, Os extends List<object>> =
    __AssignDeep<O, Os> extends infer X
    ? Cast<X, object>
    : never

/**
Assign a list of [[Object]] into **`O`** with [[Merge]] (last-in overrides)
@param O to assign to
@param Os to assign
@returns [[Object]]
@example
```ts
```
*/
export type AssignDeep<O extends object, Os extends List<object>> =
    O extends unknown
    ? Os extends unknown
      ? _AssignDeep<O, Os>
      : never
    : never

type t = AssignDeep<{}, [{a: {b: 1}}, {a: {c: 1}}, {a: {c: 1}}, {a: {c: 1}}, {a: {c: 1}}, {a: {c: 3}}]>
```

**Comment by mesqueeb** [comment]
@pirix-gh 
Hi, your snippet is the exact same thing as in my PR. 😄 
But sadly, it still doesn't work for my use case.

<img width="735" alt="image" src="https://user-images.githubusercontent.com/3253920/74436425-c6cd3c00-4ea9-11ea-8f95-639829036591.png">

You can see `test` says `any`.

My JavaScript "deep" merge function has some rules I wanted to enforce. Mainly:
- when merging `{a: number}, {a: string}` it should become `{a: string}`→ it needs to keep the latter type in the merged result.
- when merging `{a: {}}, {a: {b: number}}` it should become `{a: {b: number}}` → only merge nested props if they both are an object. (this is to be checked at any depth level)

So I think this is the reason I tried to use this function in my solution:
```ts
type Assign<T1, T2> = [IsPlainObject<T1>, IsPlainObject<T2>] extends [true, true] ? O.Merge<T1, T2, 'deep'> : T2
```
This, to my knowledge should say:
- if both types are plain objects, merge them, if not, keep the latter type.

But two problems remain:
1. Even if I change the type checker, `IsPlainObject` for `IsObject` like so:
```ts
type IsObject<T> = T extends object ? true : false
```
my Assign function still gives the error when trying to use your `O.Merge` like so:
<img width="1202" alt="image" src="https://user-images.githubusercontent.com/3253920/74437338-4c052080-4eab-11ea-8e74-bb0eea41057b.png">

2. The typecheck I do at Assign is only on the top level of each object, but I need to check this on each subprop to be able to merge the two objects as per my rules explained above.

Do you have any advice for me? If you can point me into the direction of places where you needed to solve a similar issue with recursiveness and type checking, I'd love to dig in!

**Comment by pirix-gh** [comment]
I made the feature request available in https://github.com/pirix-gh/ts-toolbelt/commit/7c684b4734dc7ee04a2e33ea3e02b1c6046c41f0

**Comment by pirix-gh** [comment]
Tests were not needed because it used already tested `Merge` & `MergeUp`.
