### ISSUE TITLE
O.Merge and O.Assign have different behaviour with optional props

### ISSUE THREAD

**Issue by mesqueeb** [pirix-gh/ts-toolbelt#92]
#### Describe your question

There seems to be different behaviour between O.Merge and O.Assign when it comes to optional props. I'm trying to create a function that "merges" an object **onto a defaults object**, so the result will always have all required props.

```ts
type Hand = {
  card: number
}
type HandWithDefaults = O.Merge<Hand, Partial<Hand>>
```
returns:
<img width="226" alt="image" src="https://user-images.githubusercontent.com/3253920/74597801-9bfd0680-50a8-11ea-9e4c-d82299e68705.png">

**however, with O.Assign, the prop is made optional:**
```ts
type HandWithDefaults2 = O.Assign<Hand, [Partial<Hand>]>
```
returns
<img width="243" alt="image" src="https://user-images.githubusercontent.com/3253920/74597811-af0fd680-50a8-11ea-952d-426b0509320b.png">

I want the exact same behaviour of O.Merge but on O.Assign.

### Use case:

My use case is simple to create a merge function that will keep all values as required, even though a Partial of the type is overwriting the defaults.

```ts
type Hand = {
  card: number
}

// this is my custom merge function that uses O.Assign in the return
function merge <T1 extends object, T2 extends object> (o1: T1, o2: T2): O.Assign<T1, [T2], 'deep'> {
  const result = Object.assign({}, o1, o2) // my custom merge function
  return result as unknown as O.Assign<T1, [T2], 'deep'>
}

function addDefaults (myHand: Partial<Hand>): Hand {
  const defaults: Hand = {
    card: 1
  }
  // here is where the error occurs:
  const result = merge(defaults, myHand)
  return result
}

// this is how I need to use an "addDefaults" function:
function shuffle (myHand: Partial<Hand>): any {
  const hand = addDefaults(myHand)
  console.log('hand → ', hand)
}
```

The error:
<img width="848" alt="image" src="https://user-images.githubusercontent.com/3253920/74597769-0c575800-50a8-11ea-8ffd-ccd2095d67d0.png">

#### Search tags, topics
#typescript #merge #assign #incompatible

**Comment by pirix-gh** [comment]
The thing is that with `Assign` the last-in wins. I'm going to release a type for this. Just hold one please.

**Comment by pirix-gh** [comment]
`npm install ts-toolbelt@6.3.0`

The utility is called `Compact`.

**Comment by mesqueeb** [comment]
@pirix-gh 
Thank you very much. The new `Compact` seems to work in my use-case.

While checking the docs I felt compelled to make a PR to add some examples to the docs.
Especially the exact differences between:
- Assign
- Compact
- Merge
- all Up variants

are a bit unclear for newer developers I think. Tbh. I still don't fully understand when I should use the `Up` variants, even after reading [this post](https://github.com/pirix-gh/ts-toolbelt/issues/65).

> The Up usually means that the type is a counterpart of another type that is able to handle Unions. It goes "up" within a union, and is also an upgrade of its non-up counterpart.

I'm not sure what this means exactly. 😅 

So perhaps I can just add one example for each of these:
- Assign
- Compact
- Merge

And then we can think of how these examples would differ with the `Up` version after that. What do you think? 😉 

So please hold on, I'll find some time this week and come up with an example for each!

**Comment by pirix-gh** [comment]
I don't have time now, sorry about that:

- Assign: Works like assign in JS, the last objects in the list overrides the previous ones.
- Compact: Works the same, but properties don't override as they merge they just complete and leave first overlapping properties untouched. This is why it's called `Compact`.
- Merge: It's simple. It merges from right to left (all the tools work from right to left).

And for the `Up` versions. They are able to deal with optional fields. I'm considering making them the default and add a `strict` option instead.

Here's an example of what they do:
```ts
type O = {
    a?: 1
}

type O1 = {
    a?: 2
    b : 3
}

type test0 = Merge<O, O1>
type test1 = MergeUp<O, O1>
```

**Comment by pirix-gh** [comment]
@mesqueeb You are free to add examples :) I'd be very glad if you could. Thank you!
