### ISSUE TITLE
Use unique symbol in Any.Type

### ISSUE THREAD

**Issue by whzx5byb** [pirix-gh/ts-toolbelt#94]
import { A } from 'ts-toolbelt';

    type S = A.Type<Object, 'foo'>;
    const s: S = {__type: 'foo'}; // expected an error, but succeed.

Use unique symbol could fix this issue.

Any/Type.ts

    export type Type<A extends any, Id extends string> =
        A & {__type: Id}
replace it with:

    const UniqueSymbol = Symbol()
    export type Type<A extends any, Id extends string> =
        A & {[K in typeof UniqueSymbol]: Id}

**Comment by pirix-gh** [comment]
Thanks for tip. It will be out in a minute.

**Comment by pirix-gh** [comment]
Issues with ts 3.9.0-dev are blocking, needs investigation. Sorry.

**Comment by whzx5byb** [comment]
> Issues with ts 3.9.0-dev are blocking, needs investigation. Sorry.

Could you please tell whats the issue?

**Comment by pirix-gh** [comment]
The tests are failing on `MergeUp` and it needs more investigation.

**Comment by pirix-gh** [comment]
fixed
