### ISSUE TITLE
Any.Equals<> is broken

### ISSUE THREAD

**Issue by AnyhowStep** [pirix-gh/ts-toolbelt#97]
#### Describe the bug
`Any.Equals<>` is broken

TS 3.0, TS 3.1, TS 3.5.1 and TS 3.8

#### Reproduce the bug
```ts

export type Equals<A1 extends any, A2 extends any> =
    (<A>() => A extends A1 ? 1 : 0) extends (<A>() => A extends A2 ? 1 : 0)
    ? 1
    : 0

interface Foo<T> {
    x : () => T
}

declare const a: Foo<Date>;
declare const b: Foo<Date | null>;

//Expected 0, Actual 1
type ShouldBe0 = Equals<typeof a, typeof b>;

```

#### Expected behavior

Expected `0`

#### Screenshots

![image](https://user-images.githubusercontent.com/5655961/76288246-aca23600-627c-11ea-887f-fcfa0d7f8645.png)

#### Additional context

http://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=16&pc=1#code/FAUwHgDg9gTgLgAjgTwiBBRAjgVwIYA2AzgDwCCAjAuHCAHYAmRCedyANAmQEzVi2NmrZAD4EAXmAJpCABTkRsgJQSxZPgKZcqAfgRUAXAgAMKmvS3yyileLUaLzHgj2GTSqTNefpR48GAASzpaGAAzPABjdAAxKCgSABUxAG8fBDAEI2VVBETgAF8AhhBIgjwYdEioOiJEPCM4hIARPFoRAG5gErKKqpq6hAAjRviSVtoEAB8EOhwCAk6AgHpljEhS2gYTTjJIuHwCfWAUNAQAZQALKHmGACEQYwlMXEJSU5AoMJZOD6-hpZAA

**Comment by pirix-gh** [comment]
fixed
